package postgres

import (
	"strings"
	"testing"

	"github.com/guiiamorim/migrateit/internal/schema"
)

func TestDialect_CreateTableWithInlineFK(t *testing.T) {
	d := NewDialect()
	tbl := &schema.Table{
		Name: "orders",
		Columns: []*schema.Column{
			{Name: "id", Definition: "bigint", Extra: "GENERATED BY DEFAULT AS IDENTITY"},
			{Name: "user_id", Definition: "bigint"},
		},
		PrimaryKey: &schema.Constraint{Name: "orders_pkey", Type: PrimaryKey, Columns: []string{"id"}},
	}
	fk := &schema.ForeignKey{Name: "fk_orders_user", Columns: []string{"user_id"},
		RefTable: "users", RefColumns: []string{"id"}, OnDelete: "CASCADE"}

	got := d.CreateTable(tbl, []*schema.ForeignKey{fk})
	wants := []string{
		`CREATE TABLE "orders"`,
		`"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`,
		`CONSTRAINT "orders_pkey" PRIMARY KEY ("id")`,
		`CONSTRAINT "fk_orders_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE`,
	}
	for _, w := range wants {
		if !strings.Contains(got, w) {
			t.Errorf("missing %q\n--- got ---\n%s", w, got)
		}
	}
}

func TestDialect_ModifyColumnEmitsGranularActions(t *testing.T) {
	d := NewDialect()
	def := "0"
	got := d.ModifyColumn("users", &schema.Column{Name: "age", Definition: "integer", Nullable: false, Default: &def})
	want := `ALTER TABLE "users" ALTER COLUMN "age" TYPE integer, ALTER COLUMN "age" SET NOT NULL, ALTER COLUMN "age" SET DEFAULT 0`
	if got != want {
		t.Errorf("\ngot:  %s\nwant: %s", got, want)
	}
}

func TestDialect_DropForeignKeyUsesDropConstraint(t *testing.T) {
	got := NewDialect().DropForeignKey("orders", &schema.ForeignKey{Name: "fk_orders_user"})
	if got != `ALTER TABLE "orders" DROP CONSTRAINT "fk_orders_user"` {
		t.Errorf("unexpected: %s", got)
	}
}

func TestDialect_PlainIndexBecomesCreateIndex(t *testing.T) {
	got := NewDialect().AddConstraint("users", &schema.Constraint{Name: "ix_email", Type: Index, Columns: []string{"email"}})
	if got != `CREATE INDEX "ix_email" ON "users" ("email")` {
		t.Errorf("unexpected: %s", got)
	}
}

func TestColumnType_MapsPostgresTypes(t *testing.T) {
	cases := map[string]schema.ColumnType{
		"character varying":           Varchar,
		"timestamp without time zone": Timestamp,
		"double precision":            Double,
		"jsonb":                       JSONB,
	}
	for in, want := range cases {
		if got := columnType(in); got != want {
			t.Errorf("columnType(%q) = %s, want %s", in, got, want)
		}
	}
}
